<?php
/** Replacement data: service information through FAQ. */
return [
        ['info-etiqueta', '<p class="tmd-maint-eyebrow">Información útil</p>', '<p class="tmd-maint-eyebrow">Información para solicitar el servicio</p>'],
        ['info-texto', 'Una descripción precisa no reemplaza la inspección, pero facilita preparar la visita y evita perder datos importantes sobre la falla.', 'Contar con información básica del equipo y de la falla nos permite comprender mejor la situación y preparar la atención técnica. Estos datos complementan la inspección que realizará nuestro personal.'],
        ['info-equipo-titulo', '<h3>Datos del equipo</h3>', '<h3>Información del equipo</h3>'],
        ['info-equipo-lista', "          <li>Marca, modelo y número interno o serial.</li>\n          <li>Tipo de montacargas y capacidad.</li>\n          <li>Ubicación y condiciones de acceso.</li>\n          <li>Horas aproximadas y turnos de trabajo.</li>", "          <li>Marca, modelo y número de serie o identificación interna.</li>\n          <li>Tipo de montacargas y capacidad de carga.</li>\n          <li>Ubicación del equipo y condiciones de acceso.</li>\n          <li>Horómetro y turnos aproximados de operación.</li>"],
        ['info-falla-titulo', '<h3>Datos de la falla</h3>', '<h3>Información de la falla</h3>'],
        ['info-falla-lista', "          <li>Qué función dejó de operar y cuándo ocurrió.</li>\n          <li>Códigos, alarmas o indicadores visibles.</li>\n          <li>Ruidos, fugas, calentamiento o pérdida de fuerza.</li>\n          <li>Reparaciones recientes o repetición del problema.</li>", "          <li>Descripción de la falla y momento en que se presentó.</li>\n          <li>Funciones que dejaron de operar o presentan comportamiento irregular.</li>\n          <li>Códigos de falla, alarmas o indicadores visibles.</li>\n          <li>Ruidos, fugas, calentamiento, vibraciones o pérdida de rendimiento.</li>\n          <li>Reparaciones recientes o antecedentes de la misma falla.</li>"],
        ['criterios-marcador', "  <section class=\"tmd-maint-section\">\n    <header class=\"tmd-maint-section__header\">\n      <p class=\"tmd-maint-eyebrow\">Criterios de servicio</p>\n      <h2>Qué puede esperar de una atención correctiva</h2>", "  <section class=\"tmd-maint-section tmd-corrective-criteria\">\n    <header class=\"tmd-maint-section__header\">\n      <p class=\"tmd-maint-eyebrow\">Criterios de servicio</p>\n      <h2>¿Qué puede esperar de nuestro servicio correctivo?</h2>"],
        ['criterio-1', '<h3>Diagnóstico primero</h3><p>La intervención se orienta a la causa probable y a las pruebas realizadas.</p>', '<h3>Diagnóstico técnico</h3><p>La intervención se define a partir de la inspección, las mediciones y las pruebas realizadas para identificar el origen de la falla.</p>'],
        ['criterio-2', '<h3>Alcance informado</h3><p>Las actividades y repuestos adicionales se comunican antes de ejecutarse.</p>', '<h3>Alcance informado</h3><p>Antes de realizar trabajos adicionales, se informa el alcance de la reparación y los repuestos requeridos para su autorización.</p>'],
        ['criterio-3', '<h3>Pruebas funcionales</h3><p>El equipo se verifica dentro de condiciones seguras antes de concluir el servicio.</p>', '<h3>Pruebas de funcionamiento</h3><p>Una vez realizada la intervención, se efectúan pruebas para verificar el funcionamiento del equipo en condiciones seguras de operación.</p>'],
        ['criterio-4', '<h3>Recomendaciones</h3><p>Se indican hallazgos que requieren seguimiento preventivo o una intervención posterior.</p>', '<h3>Recomendaciones técnicas</h3><p>Al finalizar, se informan los hallazgos relevantes y las recomendaciones de mantenimiento o intervenciones que requieran seguimiento.</p>'],
        ['despues-titulo', 'Evite que la falla se repita por la misma condición de uso', 'Prevenga la repetición de la falla'],
        ['despues-texto', 'Cuando el origen está relacionado con operación, carga, ambiente o mantenimiento pendiente, la reparación debe acompañarse de acciones de seguimiento.', 'Cuando la causa de una falla está relacionada con las condiciones de operación, los ciclos de carga, el entorno de trabajo o necesidades de mantenimiento, es importante establecer acciones de seguimiento que ayuden a prevenir su recurrencia.'],
        ['despues-lista', "        <li>Registrar la falla, la causa identificada y la solución aplicada.</li>\n        <li>Revisar hábitos de operación y carga relacionados con el evento.</li>\n        <li>Programar la inspección de componentes con desgaste asociado.</li>\n        <li>Confirmar que el operador reconoce alarmas y señales críticas.</li>\n        <li>Incorporar el equipo a un plan preventivo cuando corresponda.</li>", "        <li>Registrar la falla, la causa identificada y la reparación realizada.</li>\n        <li>Revisar las condiciones de operación y los ciclos de carga relacionados con la falla.</li>\n        <li>Programar la inspección de componentes que presenten desgaste o requieran seguimiento.</li>\n        <li>Verificar que los operadores reconozcan alarmas y señales de funcionamiento anormal.</li>\n        <li>Incluir el equipo en un plan de mantenimiento preventivo cuando sea necesario.</li>"],
        ['faq-titulo', '<h2>Sobre el mantenimiento correctivo</h2>', '<h2>Preguntas frecuentes sobre mantenimiento correctivo</h2>'],
        ['faq-1', '<details><summary>¿Pueden cotizar una reparación solo con una fotografía?</summary><p>Una imagen o video ayuda a entender el síntoma, pero muchas fallas necesitan medición e inspección. La cotización definitiva depende del diagnóstico y del alcance confirmado.</p></details>', '<details><summary>¿Pueden cotizar una reparación solo con una fotografía o video?</summary><p>Puede orientar la revisión, pero la cotización definitiva depende del diagnóstico técnico.</p></details>'],
        ['faq-2', '<details><summary>¿Todo código de alarma significa que debe cambiarse una pieza?</summary><p>No necesariamente. Un código orienta la revisión, pero puede estar relacionado con conexiones, alimentación, sensores, configuración u otras condiciones que deben comprobarse.</p></details>', '<details><summary>¿Todo código de alarma significa que debe cambiarse un componente?</summary><p>No. El código orienta el diagnóstico, pero es necesario verificar la causa antes de reemplazar componentes.</p></details>'],
        ['faq-3', '<details><summary>¿Qué pasa si durante la reparación aparece otra falla?</summary><p>El nuevo hallazgo debe informarse con su impacto y alcance. No deberían ejecutarse actividades adicionales sin la autorización correspondiente.</p></details>', '<details><summary>¿Qué sucede si durante la reparación se identifica otra falla?</summary><p>Se informa el hallazgo y cualquier trabajo adicional se realiza con autorización del cliente.</p></details>'],
        ['faq-4', '<details><summary>¿Cuándo puede regresar el equipo a operación?</summary><p>Después de completar la reparación autorizada, realizar las pruebas aplicables y confirmar que las funciones intervenidas responden de manera adecuada.</p></details>', '<details><summary>¿Cuándo puede regresar el equipo a operación?</summary><p>Después de finalizar la reparación y verificar su funcionamiento mediante las pruebas correspondientes.</p></details>'],
];
